### ISSUE TITLE
HowTo flash pi with this

### ISSUE THREAD

**Issue by JericoPablo** [kleo/fusee-alpestre#2]
Hi,

im quite new to the switch world with all the rcm stuff.
Could you by anychance write a small HowTo get this as an image on the pi?

**Comment by JericoPablo** [comment]
okay i helped myself out with - of course - ChatGPT. 
I run the make-image script on a WSL instance to get the image.

But somehow i run into 

`fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  busybox-initscripts (no such package):
    required by: world[busybox-initscripts]`

it seems like it have been renamed, removed, or replaced in the latest Alpine Linux repositories right? or am i doing smth wrong?

**Comment by kleo** [comment]
Latest images are very outdated [hekate v6.0.4 & Nyx v1.5.3](https://github.com/CTCaer/hekate/releases/tag/v6.0.4)  [Atmosphère 1.5.3](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.3). Not sure if you could still use them.

Quick guide:
1. Download zip from releases
2. `unzip fusee-alpestre-atmosphere.zip`
3. `sudo dd if=fusee-alpestre-atmosphere.img of=<sdcard> conv=fsync status=progress`

Yesterday I also attempted to update this. Due to the recent Yuzu lawsuit the payload launcher created by Qyriad I used on this project is no longer available. 

https://github.com/kleo/fusee-alpestre/blob/b2917d16063995ad87eb2337e1248562e3ffb8b2/bootstrap/fusee.sh#L7

**Comment by borntohonk** [comment]
> Latest images are very outdated [hekate v6.0.4 & Nyx v1.5.3](https://github.com/CTCaer/hekate/releases/tag/v6.0.4) [Atmosphère 1.5.3](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.3). Not sure if you could still use them.
> 
> Quick guide:
> 
>     1. Download zip from releases
> 
>     2. `unzip fusee-alpestre-atmosphere.zip`
> 
>     3. `sudo dd if=fusee-alpestre-atmosphere.img of=<sdcard> conv=fsync status=progress`
> 
> 
> Yesterday I also attempted to update this project. Due to the recent Yuzu lawsuit the payload launcher created by Qyriad I used on this project is no longer available. https://chaos.social/@ktemkin/112040819004020997
> 
> https://github.com/kleo/fusee-alpestre/blob/b2917d16063995ad87eb2337e1248562e3ffb8b2/bootstrap/fusee.sh#L7

`https://github.com/borntohonk/fusee-launcher/archive/refs/tags/1.0.zip`

https://github.com/kleo/fusee-alpestre/pull/3

here you go,not sure why you need this, just copy `modchipd.sh` and `fusee-launcher.py` into your own repository.

**Comment by kleo** [comment]
Updated fusee-alpestre payloads. Thanks again @borntohonk!

**Comment by JericoPablo** [comment]
Thank you for sharing! ill download and flash it to my sdcard. Lets see if it will work. Going to japan on friday, not sure if the switch will turn off on the plane somewhen. Need this as an backup 👍
